### ISSUE TITLE
Compilation error after #10

### ISSUE THREAD

**Issue by moononournation** [bitbank2/JPEGDEC#12] opened 2020-12-08 09:49 UTC
After update to #10 the follow compilation error appear:
In file included from ~/Documents/Arduino/libraries/JPEGDEC/src/JPEGDEC.h:26:0,
                 from ~/Documents/Arduino/libraries/JPEGDEC/src/jpeg.c:23:
~/Documents/Arduino/hardware/espressif/esp32/libraries/FS/src/FS.h:24:18: fatal error: memory: No such file or directory
compilation terminated.

**Comment by bitbank2** [comment] 2020-12-08 13:19
I just pushed a fix for other issues, but cannot reproduce the problem you're seeing with FS.h. Please do a git pull and see if it works now.

**Comment by moononournation** [comment] 2020-12-08 13:27
checked same error message

**Comment by moononournation** [comment] 2020-12-08 13:27
I am using Arduino IDE 1.8.13

**Comment by moononournation** [comment] 2020-12-08 13:33
just checked it can fix if rename jpeg.c to jpeg.cpp

**Comment by bitbank2** [comment] 2020-12-08 14:02
That sounds like a build issue. Are you using the Arduino IDE?

**Comment by moononournation** [comment] 2020-12-09 03:30
I am using Arduino IDE 1.8.13 and the error only appear on ESP8266 and ESP32.

**Closed** 2020-12-20 20:23 UTC
